source 'https://github.com/CocoaPods/Specs.git'

target 'IRLSizeExample', :exclusive => true do
  pod "IRLSize", :path => "../IRLSize.podspec"
end

target 'Tests', :exclusive => true do
  pod "IRLSize", :path => "../IRLSize.podspec"
  pod "Kiwi", :inhibit_warnings => true
end
